### ISSUE TITLE
rendering json data

### ISSUE THREAD

**Issue by rageshpillai** [szymon33/dhtmlxgantt#1]
how to render multiple model data in single json call.

**Comment by szymon33** [comment]
It's easy. Assuming that you have 2 models: `Task` and `GanntLink`. You can use i.ex. `map` method and build your pattern 

``` ruby
  render :json => { ... }, status: :ok 
```

like this:

``` ruby
def data
    tasks = Task.all
    links = GanttLink.all

    render :json => {
      data: tasks.map do |task|
      {
        id: task.id,
        text: task.text,
        start_date: task.start_date,
        duration: task.duration,
        progress: task.progress,
        parent: task.parent
      }
      end,
      links: links.map do |link|
      {
        id: link.id,
        source: link.source, 
        target: link.target, 
        type: link.gtype
      }  
      end
    }, status: :ok
end  
```

**Comment by rageshpillai** [comment]
this is my code cant render in proper format

 render :json => {
        data: @@gant.map do |hoshin|

```
          {
           id: hoshin.id,
           text: hoshin.name,
           start_date:  "01-04-2013",
           end_date: "01-04-2013",
            leader: "nnpq"

                  }
      hoshin.hoshin_tasks.map |task|


          {
           id: task.id,
           text: task.name,
           start_date:  "01-04-2013",
           end_date: "01-04-2013",
            leader: "nnpq"

                  }
     end             
    end
}, status: :ok 
```

i have 2  models hoshin and hoshin tasks. hoshin is project and hoshin task is the task assigened to the particular hoshin.. then how can render data with same data value.

**Comment by szymon33** [comment]
I wouldn't nest it.
First try to setup correct collections for `hoshins` and `hoshin_tasks` . It could work like this:

``` ruby
  hoshins = Hoshin.all
  hoshin_tasks = HoshinTask.all
```

then render JSON like this

``` ruby
render :json => {
  data: hoshins.map do |hoshin|
  {
    id: hoshin.id,
    text: hoshin.name,
    leader: "nnpq",
    type: "project"
  }
  end,
  hoshin_tasks.map |task|
  {
    id: task.id,
    text: task.name,
    start_date:  "01-04-2013",
    end_date: "01-04-2013",
    leader: "nnpq",
    type: "task"
  }
  end             
}, status: :ok 
```

**Comment by szymon33** [comment]
Please note that Project model in dhtmlx has no start_date and end_date. start_date and end_date come from its subtasks. 

http://docs.dhtmlx.com/gantt/desktop__task_types.html

**Comment by rageshpillai** [comment]
but only render tasks project does not appear in chart
hoshin=Hoshin.hoshins_in_business_unit(get_or_set_session_business_unit_id(@@bu_id_in_session))
hoshin_task=Hoshin.gantt_chart_report(current_user,@@bu_id_in_session)
render :json => {
        data: @@gant.map do |h|

```
          {
           id: h.id,
           text: h.name,
           open:true,
            leader: "nnpq"

                  }

    end,


  data: @gantt.map do |hoshin|

     hoshin_start_date=hoshin.task_start_date ? hoshin.task_start_date.to_date.strftime("%m/%d/%Y") : nil
     hoshin_end_date=hoshin.etc ? hoshin.etc.to_date.strftime("%m/%d/%Y") : nil
     p "parent id",hoshin.hoshin_id
    # parent_id=hoshin.hoshin_id==78 ?  0 : 78

         {
          # id: hoshin.hoshin_id,
          text: hoshin.hoshin_name,
          start_date: hoshin_start_date,
          end_date:  hoshin_end_date,
          leader: hoshin.task_leader
          #parent: parent_id

        }   


        end
  }, status: :ok 
```

**Comment by rageshpillai** [comment]
sry
but only render tasks project does not appear in chart
hoshin=Hoshin.hoshins_in_business_unit(get_or_set_session_business_unit_id(@@bu_id_in_session))
hoshin_task=Hoshin.gantt_chart_report(current_user,@@bu_id_in_session)
render :json => {
data: hoshin.map do |h|

```
      {
       id: h.id,
       text: h.name,
       open:true,
        leader: "nnpq"

              }

end,
```

  data: hoshin_task.map do |hoshin|

```
 hoshin_start_date=hoshin.task_start_date ? hoshin.task_start_date.to_date.strftime("%m/%d/%Y") : nil
 hoshin_end_date=hoshin.etc ? hoshin.etc.to_date.strftime("%m/%d/%Y") : nil
 p "parent id",hoshin.hoshin_id
# parent_id=hoshin.hoshin_id==78 ?  0 : 78

     {
      # id: hoshin.hoshin_id,
      text: hoshin.hoshin_name,
      start_date: hoshin_start_date,
      end_date:  hoshin_end_date,
      leader: hoshin.task_leader
      #parent: parent_id

    }   


    end
```

  }, status: :ok

**Comment by szymon33** [comment]
I will expand this repo and add Project model in the next commit.
I think that you have to add to json
`type: "project"`
I have modified my previous answer.

**Comment by rageshpillai** [comment]
its urgent pls update soon

**Comment by rageshpillai** [comment]
pls do soon

## 

## 

Thanks and Regards,
RAGESH.R.PILLAI

**Comment by rageshpillai** [comment]
hi,
its very urgent. i have a work related to gantt chart and want to close
very soon pls update the repo asap..

## 

## 

Thanks and Regards,
RAGESH.R.PILLAI

**Comment by szymon33** [comment]
ok

**Comment by szymon33** [comment]
Render with Project model is more complex, but I have just updated repo and it should be fine now.
