### ISSUE TITLE
how to render json data with differnt model with same data value

### ISSUE THREAD

**Issue by rageshpillai** [szymon33/dhtmlxgantt#2]
his is my code cant render in proper format

render :json => {
data: @@gant.map do |hoshin|

```
      {
       id: hoshin.id,
       text: hoshin.name,
       start_date:  "01-04-2013",
       end_date: "01-04-2013",
        leader: "nnpq"

              }
  hoshin.hoshin_tasks.map |task|


      {
       id: task.id,
       text: task.name,
       start_date:  "01-04-2013",
       end_date: "01-04-2013",
        leader: "nnpq"

              }
 end             
end
```

}, status: :ok 
i have 2 models hoshin and hoshin tasks. hoshin is project and hoshin task is the task assigened to the particular hoshin.. then how can render data with same data value.

**Comment by szymon33** [comment]
Last commit includes the Project model.

**Comment by rageshpillai** [comment]
how to set deafult value for start date if date is empty

## 

## 

Thanks and Regards,
RAGESH.R.PILLAI

**Comment by rageshpillai** [comment]
K thanks alot

## 

## 

Thanks and Regards,
RAGESH.R.PILLAI

**Comment by szymon33** [comment]
Of the Task or of the Project?

**Comment by rageshpillai** [comment]
both task and project. dont show the date in date field field of gantt
chart. if start date date and end date ids empty..

## 

## 

Thanks and Regards,
RAGESH.R.PILLAI

**Comment by rageshpillai** [comment]
please see the image

## 

## 

Thanks and Regards,
RAGESH.R.PILLAI

**Comment by szymon33** [comment]
Hi Ragesh,

There is no need for default `start_date` and `duration` (not `end_date`). The chart handles it by taking project `start_date` which is a `start_date` of erliest task of the project. However, I have set the `start_date` and `duration` just in case , right now.

https://github.com/szymon33/dhtmlxgantt/blob/master/app/models/task.rb

Also, I can not see your image but you can see mine:

![Screentshot](https://raw.github.com/szymon33/dhtmlxgantt/master/screenshot2.png)

Above dialog works even without these defaults.
Just clone the repo, setup database, run `rake db:setup` and run a browser.

Thanks,

**Comment by rageshpillai** [comment]
k. i just want to show only the gantt, there is no task creation from this
chart

## 

## 

Thanks and Regards,
RAGESH.R.PILLAI

**Comment by rageshpillai** [comment]
[image: Inline image 1]

## 

## 

Thanks and Regards,
RAGESH.R.PILLAI

**Comment by rageshpillai** [comment]
or how to disable project start ate and end date calculation

## 

## 

Thanks and Regards,
RAGESH.R.PILLAI

**Comment by szymon33** [comment]
Yes, there is. Find the green plus icon in the left table and you will see the dialog window presented before.

**Comment by rageshpillai** [comment]
project does not show start date and end date

## 

## 

Thanks and Regards,
RAGESH.R.PILLAI

**Comment by rageshpillai** [comment]
project does not want to show start date and end date

## 

## 

Thanks and Regards,
RAGESH.R.PILLAI

**Comment by szymon33** [comment]
There is no `end_date` but `duration`

Just clone the repo, setup database, `run rake db:setup` and run a browser.

Your chart should look like this. The first line is a project.

![Screentshot](https://raw.github.com/szymon33/dhtmlxgantt/master/screenshot1.png)

Project task is a task that starts, when its earliest child task starts, and ends, when its latest child ends. It doesn't have its own start_date and end_date. It's calculated.

**Comment by rageshpillai** [comment]
I have an issue related to date.. invalid date is displayed in start date.
any formating option needed to filter date in json format

## 

## 

Thanks and Regards,
RAGESH.R.PILLAI

**Comment by szymon33** [comment]
Maybe, try to setup `config.time_zone` parameter in your `application.rb` file or you have something out of place in your `index.html.erb` (template file) with 

``` javascript
gantt.config.xml_date = "%Y-%m-%d %H:%i:%s";
```

I checked everything yesterday and put some new code in there. It works like a charm, at least in this case.

**Comment by rageshpillai** [comment]
how to change icon of the task

## 

## 

Thanks and Regards,
RAGESH.R.PILLAI

**Comment by rageshpillai** [comment]
hi
in my project start date and end date is not mandatory. how to show chart
if this field is nil or emty. any idea?
or how to pass nil value in json

## 

## 

Thanks and Regards,
RAGESH.R.PILLAI

**Comment by szymon33** [comment]
Hi,

The idea of Gantt chart is to preent tasks on timeline. So, if your task has no start_date or duration then chart should not show it. Overwize it has no sense. I will add extra scope to the Task model to filter out 'invalid' tasks. You can write in your app i.ex. above the chart a message like 'only tasks with date appear here'.
In case of question about the icon I can not see any icon here but you can change a CSS skin of the whole diagram.

**Comment by rageshpillai** [comment]
icon can be changed by using this fns

/gantt.templates.grid_file = function(item) {
  //  return "<div class='gantt_tree_icon gantt_file' style=
background-image:url('<%=asset_path 'add_action_items.png' %>)></div>";
  //  $(".gantt_tree_icon").addClass('changeIcon')
//};

but it could not retrieve the exact url of the image..

## 

## 

Thanks and Regards,
RAGESH.R.PILLAI

**Comment by rageshpillai** [comment]
how to custom fields when adding new tasks by clicking +

## 

## 

Thanks and Regards,
RAGESH.R.PILLAI

**Comment by szymon33** [comment]
In case of your own `add_action_items.png` image the asset pipeline works like a harm. So, you can try to overwrite default CSS 

``` css
.gantt_add, .gantt_grid_head_add {
  background-image: ....
}
```

In case of custom fields when adding new task take a look at below documentation:
http://docs.dhtmlx.com/gantt/desktop__custom_editor.html

Cheers,

**Comment by rageshpillai** [comment]
Thank u. if u dont mind can pls give me ur mail id.

## 

## 

Thanks and Regards,
RAGESH.R.PILLAI
